**Numpy** -- Numerical Python
<br>
Advantages of numpy <br>
1. Allows several Mathematical Operations<br>
2. Faster operations

In [ ]:
import numpy as np

List Vs Numpy - Time Taken

In [ ]:
from time import process_time

Time Taken by the list

In [10]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print('Process Time Required : '+ str(end_time-start_time))

Process Time Required : 0.0006727299999997882


Time Taken by Numpy array

In [11]:
numpy_array = np.array([i for i in range(10000)])

start_time = process_time()

numpy_array += 5

end_time = process_time()

print('Processing Time Required : ' + str(end_time - start_time))

Processing Time Required : 0.0011343900000007068


Numpy Array

In [12]:
# list
list1  = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
# Create a numpy array
np_array = np.array(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [14]:
# Creating 1D Array
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [15]:
# Creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
b.shape

(2, 4)

In [16]:
# specifying datatype
c = np.array([[1,2,3,4],[5,6,7,8]], dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [17]:
# Create numpy array of zeros
x = np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# creating numpy array of ones
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# array of a particular value
z = np.full((4,5),5)
z

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [24]:
# create an identity matrix
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# create a numpy array with random values
r = np.random.random((4,5))
r

array([[0.49404702, 0.86339708, 0.99383926, 0.09164521, 0.61810149],
       [0.42465096, 0.70885379, 0.55616055, 0.99739319, 0.92218587],
       [0.84587583, 0.49675262, 0.28422527, 0.43502245, 0.0645335 ],
       [0.8757277 , 0.44749666, 0.29110115, 0.10750127, 0.26849839]])

In [26]:
# random integer values array within a specific range
r = np.random.randint(10,100,(3,5))
r

array([[96, 86, 61, 68, 90],
       [87, 77, 63, 29, 43],
       [44, 79, 35, 29, 36]])

In [31]:
# array of evenly spaced values --> specifying the number of values required
arr = np.linspace(10,30,5, dtype = int)
arr

array([10, 15, 20, 25, 30])

In [32]:
# array of evenly spaced values --> specifying the step
arr = np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [33]:
# convert a list to a numpy array
list2 = [9,8,7,6,5,4,3,2,1]

arr = np.asarray(list2)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

Mathematical Operaion in Numpy

In [35]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [38]:
print('a+b : ' , a+b)
print('b-a : ' ,b-a)
print('a*b : ' ,a*b)
print('b/a: ' ,b/a)

a+b :  [[14 16 18]
 [23 22 11]
 [20 17 23]]
b-a :  [[12  8  4]
 [ 9 10 11]
 [16  3 13]]
a*b :  [[ 13  48  77]
 [112  96   0]
 [ 36  70  90]]
b/a:  [[13.          3.          1.57142857]
 [ 2.28571429  2.66666667         inf]
 [ 9.          1.42857143  3.6       ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [39]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 16 18]
 [23 22 11]
 [20 17 23]]
[[-12  -8  -4]
 [ -9 -10 -11]
 [-16  -3 -13]]
[[ 13  48  77]
 [112  96   0]
 [ 36  70  90]]
[[0.07692308 0.33333333 0.63636364]
 [0.4375     0.375      0.        ]
 [0.11111111 0.7        0.27777778]]


Array Manipulation

In [40]:
arr = np.random.randint(0,10,(2,3))
print(arr)
print(arr.shape)

[[4 8 2]
 [2 0 9]]
(2, 3)


In [42]:
# Transpose
trans = np.transpose(arr)
trans

array([[4, 2],
       [8, 0],
       [2, 9]])

In [43]:
# OR
trans = arr.T
trans

array([[4, 2],
       [8, 0],
       [2, 9]])

In [45]:
# Reshaping the array
res = arr.reshape(3,2)
res

array([[4, 8],
       [2, 2],
       [0, 9]])